.MODEL SMALL
.STACK 100H
.DATA
.CODE

PROC MAIN
MOV BX,0X600
MOV SI,0X1001
MOV DI,0X1000
MOV BP,0X1234
;MOV [BX+ SI+DI],0XABCD ; IT IS NOT ALLOWED SO ITS INVALID AS WE CAN'T USE INDEX REGISTERS MORE THAN 1 AT THE SAME TIME
;MOV [BP+BX],0XABCD ; SIMILARLY WE CAN'T USE BASE REGISTERS AT THE SAME TIME
;MOV BX,BP   
;MOV SS,BX
MOV [BP],0XABCD
MAIN ENDP
ENDP
.EXIT