.MODEL SMALL

.STACK 1000H

.DATA 

2D_ARRAY DB 0X01,0X26
         DB 0X03,0X04
                             
NUM_ROWS EQU 2                             

NUM_COLS EQU 2

ELE_SIZE EQU 1

COL_IDX EQU 1; THAT'S THE INDEX OF THE COLUMN WE WANT TO ACCESS


          

.CODE     
         
MOV AX,@data         

MOV DS,AX  

MOV AH, 0H

MOV AL,0X00; ROW'S INDEX     


 
MOV BL,NUM_COLS     
                         
MUL BL;AL = ROW'S INDEX * NUM_COLS

ADD AL, COL_IDX           

MOV BL, ELE_SIZE

MUL BL; AL = (ROW'S INDEX * NUM_COLS)*ELE_SIZE

; NOW TO MAKE BASE_ADDRESS + (ROW'S INDEX * NUM_COLS)*ELE_SIZE

;WE'LL HAVE TO JUST ADD BASE ADDRESS OF OUR 2DARRAY IN AL 

MOV BL ,OFFSET 2D_ARRAY; THAT'S THE BASE ADDRESS OF OUR 2D ARRAY IN BX 

ADD BX, AX; AS AH = 0H SO WE SAFELY PLACE AX

;NOW BX HOLDS THE FULL ADDRESS OF INDEX [1,1] 

MOV AL,[BX]


