.MODEL SMALL

.STACK 1000H

.DATA 

ARRAY DW 0XABCD,0X1234  
ARRAY2 DW 0X4567,0X8911

.CODE     
         
MOV AX,@data         
         
MOV DS,AX

MOV AX,[ARRAY]
                       
mov ax,0x1234

MOV [ARRAY], AX; AB YAHA ARRAY K FIRST INDEX PE VALUE 1234 SET HOGI 
;WHICH MEANS ARRAY KA CONTENT CHANGE HO GA BUT LOCATION NAHI JAHA WO SOTORE HE 

MOV AX,[ARRAY]

MOV AX,[ARRAY2]   ; NOW AX MEIN 2ND ARRAY KA 0TH INDEX KA DATA AAYE GA