.MODEL SMALL
.STACK 100H
.DATA
.CODE

PROC    MAIN
     ;FOR 8-BIT THE RESULT WILL BE STORE IN AX AS BYTE*BYTE MIGHT REQUIRE 16 BIT 
     ;REGISTER TO STORE RESULT
     MOV AL, 05H        
     MOV BL, 03H        
     MUL BL     
     ; FOR 16-BIT THE RESULT WILL BE STORE IN TWO REGISTER AS WORD*WORD
     ;MIGHT REQUIRE 32-BIT REGISTERS TO STORE RESULT SO WE DIVIDE HIGH AND LOW
     ;INTO TWO 16-BIT REGISTERS FIRST IS DX USED FOR HIGH AND SECOND IS AX USED FOR LOW
     MOV AX,0XADFF
     MOV BX,0X1234
     MUL BX ;RESULT WILL BE STORE IN DX:AX
    
    
MAIN ENDP
.EXIT